### ISSUE TITLE
Add Styles option to target Tabels

### ISSUE THREAD

**Issue by mikezimm** [mikezimm/PageInfo#117]
## To allow you to change the color or border styles of tables.
aka primary to make the table borders transparent.

Typical structure

```html
<div class="canvasRteResponsiveTable">
  <div class="tableWrapper">
    <table class=" cke_show_border">
      <tbody>
        <tr>
          <td></td>
          <td> </td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td> </td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td> </td>
          <td></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
```

**Comment by mikezimm** [comment]
## Maybe target this css:

```css
 .canvasRteResponsiveTable td {
       border-color: transparent !important;
}
```
