### ISSUE TITLE
Bulletted text in forceWhiteText not white

### ISSUE THREAD

**Issue by mikezimm** [mikezimm/PageInfo#137]
## test:  /a1-tenant-group-accounting-policies.aspx

![image](https://github.com/mikezimm/PageInfo/assets/49648086/5fdd04c4-08e6-47b8-94ef-4006c4a0a11d)

**Comment by mikezimm** [comment]
## Maybe add color: white to .rte-webpart

```css
.rte-webpart {
  color: white
}
```
