### ISSUE TITLE
Page Heading issue when forceWhiteText

### ISSUE THREAD

**Issue by mikezimm** [mikezimm/PageInfo#138]
https://github.com/mikezimm/PageInfo/issues/137

![image](https://github.com/mikezimm/PageInfo/assets/49648086/2b8193f5-d131-4a62-a858-8a9e4b38f55b)

**Comment by mikezimm** [comment]
Found the default background image is causing issue

![image](https://github.com/mikezimm/PageInfo/assets/49648086/b40b2a7a-ba6a-4c6c-9cf7-798dd7a9875d)

**Comment by mikezimm** [comment]
```css

.forceWhiteText [data-automation-id="titleRegionBackgroundImage"] img {
  transition: ....
  opacity: 0
}

```
