### ISSUE TITLE
Review scroll bar options

### ISSUE THREAD

**Issue by mikezimm** [mikezimm/PageInfo#28]
## Currently, there is a gap for page scroll bar.
This can be confusing.

Evaluate alternate css which shows scroll bar for web part when pinned.
Scroll bar really should be there for longer TOC anyway.
But when using a scroll bar in web part, it would get confused with page scroll bar.

Lesser of 2 evils, use this css.
On the plus side, the toggle expand button does not shift.
On the down side, there is a noticable flicker on the page.
     NOTE:  The flicker is due to the scroll bar going visible while height is adjusting.

Maybe for now, code it as an option the user can choose.
Then on future update, we can just force one alternative or the other without the user having to update all instances.

TEST NOTES:
Need to make 'hidden' on pinMeMini or else you get a tiny scroll bar and can scroll the banner off the page and lose it.
Need to use 'overlay' to make sure the scroll bar does not shift the pin icons to the left

**Comment by mikezimm** [comment]
## Changes:
```css

.pinMeFull {
    right: 15px !important;  <== REMOVE
}

.pinMeTop {
    overlay-y: overlay;
}

.pinMeMini {
    overlay-y: hidden;
    padding-right: 15px;  <== REMOVE
}
```


![image](https://user-images.githubusercontent.com/49648086/167498385-8cdd0e10-3011-4470-8391-0ac33941b587.png)

![image](https://user-images.githubusercontent.com/49648086/167498399-d19ee0ac-a4e1-4319-bcdc-a9a259ba5d54.png)
